### ISSUE TITLE
Roadmap of potential features and fixes

### ISSUE THREAD

**Issue by javierhonduco** [javierhonduco/rbperf#2]
Some of the things I have planned:

- UX
  - [x] Better error handling (e.g. when providing a wrong syscall tracepoint name, we don't handle that nicely and the UX is bad) (https://github.com/javierhonduco/rbperf/commit/2abb8c0c49ad6e6ad1f6fa6f600fea95da5c3c62)
  - [x] Allow running tests and whatnot with cargo (https://github.com/javierhonduco/rbperf/commit/7c14cd0328f339ac6b9bf337f436d2c11970e2ca)
  - [x] Add info subcommand to show environmental details that might affect rbperf to aid debugging (https://github.com/javierhonduco/rbperf/commit/e81748a3861723e8891c28836467e147afbe2e8f)
- Quality
  - [x] Add tests for C data structure parsing and "serialisation". Run valgrind / asan on them, too (https://github.com/javierhonduco/rbperf/commit/2e3d1c017be1082395e2819955aa0ecae65818da)
  - [x] Compile BPF code with warnings on (https://github.com/javierhonduco/rbperf/commit/cb0e7b4be6e9c3ad433ddd1bfb78eee8bbf21a1b)
  - [x] Gather error statistics (right now they are mixed / not well categorised, e.g. a map can fail to write in kernel or to read from in userspace) (https://github.com/javierhonduco/rbperf/commit/4de5dee16e3ad68304057bb52e7c6cc5e09b14c8)
  - [x] Upstream elfutils and zlib static linking patches (https://github.com/libbpf/libbpf-sys/commit/371a85d2b453b6998bc91a09bb5f43ff45e521eb, https://github.com/libbpf/libbpf-rs/commit/5bed52a25fba063c871499c54a5ffab63d32dd08)
  - [x] Add tests for big stacks that require BPF tail-calls (https://github.com/javierhonduco/rbperf/commit/b474d3fa4a8a9b3bf8558134c43df928b5708454)
  - [x] Address PID reuse race condition: ( https://github.com/javierhonduco/rbperf/commit/272c8f3087b9f85c092ffccfbd131088e6b7d21d)
  - [ ] Verify that frames that we think are native are indeed native frames (https://github.com/javierhonduco/rbperf/blob/422c5ca6ffd0d7693/src/bpf/rbperf.bpf.c#L235)
- BPF
  - [x] Logging is enabled by default in the BPF program. This has high overhead and it is not needed most of the time (https://github.com/javierhonduco/rbperf/commit/422c5ca6ffd0d7693106b415d1daa742f84dcbc7)
  - [x] Evaluate using ring buffers 
    - [x] Add it as opt-in (https://github.com/javierhonduco/rbperf/commit/8a1e048b0684f0b8d89b87e9b9d3e7b7e6f8425f)
    - [x] Run some tests to see how it behaviour compares to perf buffers
- Docs
  - Add a document on architecture, as well as in-depth comments in the BPF code
  - How to debug issues
  - How to add support for Ruby versions

-----

- New features
  - Binary disk format
  - More output formats (folded stacks, chrome tracing, raw?) 
  - Ensure it works in arm64
  - C function tracing, both from cruby or the libraries it dynamically links to (uprobes)

-----
- Experimental ideas
  - Allocation tracing (w/ mem leak detection)
  - Request-specific data
-----
- Other
  - [x] Ensure we work with YJIT (asked in https://github.com/Shopify/yjit/. It works so far, but this might change)
  - [ ] Add git revision to the future info subcommand and in the BPF's metadata section
-----

- Release
  - [x] Publish x86_64 binaries

-----

Simplify execution context fetching:

```
(gdb) p/x ruby_current_vm_ptr->ractor->main_thread->ec
$1 = 0x20729b0
(gdb) p/x ruby_current_ec
$2 = 0x20729b0
```
